In [1]:
A = (1,1,1)
C = (3,1,3)

In [3]:
A-C

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [4]:
import numpy as np, matplotlib.pyplot as pl

In [5]:
A = np.array(A)
C = np.array(C)

In [6]:
A+C

array([4, 2, 4])

In [7]:
A-C

array([-2,  0, -2])

In [8]:
np.dot(A,C)

7

In [9]:
np.cross(A,C)

array([ 2,  0, -2])

In [10]:
help(np.cross)

Help on function cross in module numpy:

cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
    Return the cross product of two (arrays of) vectors.
    
    The cross product of `a` and `b` in :math:`R^3` is a vector perpendicular
    to both `a` and `b`.  If `a` and `b` are arrays of vectors, the vectors
    are defined by the last axis of `a` and `b` by default, and these axes
    can have dimensions 2 or 3.  Where the dimension of either `a` or `b` is
    2, the third component of the input vector is assumed to be zero and the
    cross product calculated accordingly.  In cases where both input vectors
    have dimension 2, the z-component of the cross product is returned.
    
    Parameters
    ----------
    a : array_like
        Components of the first vector(s).
    b : array_like
        Components of the second vector(s).
    axisa : int, optional
        Axis of `a` that defines the vector(s).  By default, the last axis.
    axisb : int, optional
        Axis of `b` that